name: Deploy Remix to GitHub Pages

on:
  push:
    branches:
      - remix

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the repo
      - name: Check out repository
        uses: actions/checkout@v2

      # 2. Use the correct Node version
      - name: Use Node 20
        uses: actions/setup-node@v2
        with:
          node-version: 20

      # 3. Install dependencies
      - name: Install dependencies
        run: yarn install

      # 4. Export your static site
      #    (Runs your script that creates the `static-export` folder)
      - name: Export static site
        run: yarn static

      # 5. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          # GitHub token
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # The folder containing your exported static files
          publish_dir: ./static-export
          cname: www.strelsov.me

          # If you want to preserve existing build history,
          # or force push, or control concurrency, etc.
          # see https://github.com/peaceiris/actions-gh-pages
